### ISSUE TITLE
请问为什么这个模型的骨骼没有在人身体里？

### ISSUE THREAD

**Issue by sunhaha123** [yanchxx/CDBA#11]
是因为使用smpl模型的骨骼原因吗？
![微信截图_20220210120849](https://user-images.githubusercontent.com/27773261/153335413-42347f97-1e0d-4670-be30-bd03a24b1952.png)
如果在导入fbx的选项里选择“自动骨骼坐标系”，骨骼确实会分布在人体里，但使用脚本驱动时，动作就不对了。
谢谢！

**Comment by yanchxx** [comment]
你这个骨骼是自己的吗，如果是自己的，肯定是要进行重新权重绑定的

**Comment by sunhaha123** [comment]
@yanch2116 好的，还麻烦问下这种是哪种绑骨方式？smpl？

**Comment by sunhaha123** [comment]
@yanch2116  是骨骼坐标系的问题，smpl模型骨骼用的是全局坐标系，敢为您之前思考过这个问题吗？

**Comment by yanchxx** [comment]
之前确实遇到过类似的问题，但是没有继续研究了，麻烦您把骨骼发到我邮箱 yanch2116@foxmail.com，我试一下

**Comment by sunhaha123** [comment]
@yanch2116 已发送到邮箱

**Comment by yanchxx** [comment]
动作不对的原因有两个。

第一个是template不对，我的是T型的，你的是A型的。
<img width="890" alt="image" src="https://user-images.githubusercontent.com/38496769/153702618-86cbdc0b-ca5e-489b-a62d-777f2830aa51.png">

第二个是骨头对应的坐标系不对，ROMP用来拟合每个骨头的旋转参数所对应的坐标系应该如下图所示。
<img width="153" alt="image" src="https://user-images.githubusercontent.com/38496769/153702625-cc8e6d0b-ebf3-45e8-b84d-627d528ffa26.png">

你的模型有些骨头的坐标系如下图所示。
<img width="124" alt="image" src="https://user-images.githubusercontent.com/38496769/153702631-9ea88d13-d211-4bc8-b470-9cc5d6bafd69.png">

这是我的看法，不知道对不对。

**Comment by sunhaha123** [comment]
@yanch2116   很感谢您之前的回答，解决了我很多疑惑。还想问下世界坐标系到骨骼局部坐标系的变换 M: A->B，在blender里是否有相应的接可以实现？

**Comment by sunhaha123** [comment]
@yanch2116 感谢您的解答，事实确实如此。
