### ISSUE TITLE
运行越久速度会越来越慢？

### ISSUE THREAD

**Issue by shaoguowen** [yanchxx/CDBA#12]
是不是会跟bone.keyframe_insert插入太多有关？

**Comment by yanchxx** [comment]
你是用的实时驱动吗

**Comment by shaoguowen** [comment]
是的

**Comment by shaoguowen** [comment]
你有试过长时间连续运行吗？

**Comment by yanchxx** [comment]
之前好像较长时间运行过，大约几十分钟应该没问题。刚刚去看了一下，实时驱动是没有插入关键帧的，只有mode等于1的时候才会使用bone.keyframe_insert。
你把背景视频啥的去掉，如果背景视频也在播放，确实会很卡，用图片当背景就不会卡了。

**Comment by shaoguowen** [comment]
好的，谢谢～是我发送的mode错了
