### ISSUE TITLE
Other characters

### ISSUE THREAD

**Issue by CheungBH** [yanchxx/CDBA#13]
Hello. Would your program support run with other characters? And are there any references about building other characters?

**Comment by yanchxx** [comment]
I found that Mixamo's X-Bot could also be driven with the plugin.
In fact, the key for the character to be driven is that the initial pose must be T-pose and the orientation of the joint should be the identity matrix. I am working on this problem now.

**Comment by Andyen512** [comment]
> I found that Mixamo's X-Bot could also be driven with the plugin. In fact, the key for the character to be driven is that the initial pose must be T-pose and the orientation of the joint should be the identity matrix. I am working on this problem now.

Sorry, I found the structure of Mixamo's X-Bot is different from yours, I'm not familiar with blender, can you tell me how to modify it, I'd like to change many Characters.

**Comment by yanchxx** [comment]
Please wait for about a week or two as I explain the skeleton structure in detail and give a tool to generate a matching skeleton for your own character. Of course, this skeleton is not precise enough and will require some manual adjustment, but it will work just fine for demonstration purposes.

**Comment by yanchxx** [comment]
Due to some reasons, skeleton generation tool cannot be provided for the time being. If you want to try other 3D characters, you can send 3D characters to my email and leave your email.
My email is yanch2116@foxmail.com.

**Comment by Andyen512** [comment]
ok, thanks. I'll contact you if I need.

**Comment by yanchxx** [comment]
Now the program support run with any character that can be rigged with mixamo.
