### ISSUE TITLE
KeyError: 'trans'

### ISSUE THREAD

**Issue by Andyen512** [yanchxx/CDBA#14]
when I ues my own npz file, it got wrongs as follows, can you tell me why?
in run
    self._target(*self._args, **self._kwargs)
  File "server.py", line 26, in tcplink
    data = getData()
  File "server.py", line 16, in getData
    temp = np.append(a[key][0]['poses'], a[key][0]['trans'])
KeyError: 'trans'

**Comment by yanchxx** [comment]
It looks like the key 'trans' is missing from your npz dict.

**Comment by Andyen512** [comment]
I just run [this](https://github.com/Arthur151/ROMP/blob/master/scripts/video.sh) to get the npz file, is there anthing I should do?

**Comment by Andyen512** [comment]
ah, I found the [line 83](https://github.com/Arthur151/ROMP/blob/master/romp/predict/base_predictor.py)was '#'
