### ISSUE TITLE
How to conver 'keypoints3d' to 'smpl_poses' and 'smpl_trans' ? 

### ISSUE THREAD

**Issue by zhangsanfeng86** [yanchxx/CDBA#15]
Hi @yanch2116 
Thank you for your wonderful work!

With the help of smpl.forward().joints , 'smpl_poses' and 'smpl_trans' conver to 'keypoints3d' .
But How to conver 'keypoints3d' to 'smpl_poses' and 'smpl_trans' ?

**Comment by yanchxx** [comment]
This is a problem that has nothing to do with this repo.
