### ISSUE TITLE
Which version of Blender are you using?

### ISSUE THREAD

**Issue by sylyt62** [yanchxx/CDBA#16]
I met the following error while running Beta.blend. I'm using blender 2.83.9. What's the expected version?

> Read blend: E:\Workspace\blender_test\addons\CharacterDriven-BlenderAddon-master\blender\Beta.blend
> 0  meshes freed
> Error: File written by newer Blender binary (290.0), expect loss of data!

**Comment by yanchxx** [comment]
I use 2.9.3

**Comment by sylyt62** [comment]
Does it support the newest 3.1.2?

**Comment by yanchxx** [comment]
No, there were problems with previous version 3.0, so I'm using 2.9.3 now.

**Comment by Altai01** [comment]
I am using 3.1.2


| |
刘德太
|
|
***@***.***
|
签名由网易邮箱大师定制


On 04/27/2022 ***@***.***> wrote：

Does it support the newest 3.1.2?
