### ISSUE TITLE
key "Pelvis" not found' 

### ISSUE THREAD

**Issue by prograguo** [yanchxx/CDBA#2]
Hello，I have some question,I can not solve it. Can you help me? Thanks!!!

`Python: Traceback (most recent call last):
  File "/home/guo/Downloads/CharacterDriven-BlenderAddon-master (1)/CharacterDriven-BlenderAddon-master/blender/Beta.blend/Text", line 42, in modal
  File "/home/guo/Downloads/CharacterDriven-BlenderAddon-master (1)/CharacterDriven-BlenderAddon-master/blender/Beta.blend/Text", line 98, in process_poses
KeyError: 'bpy_prop_collection[key]: key "Pelvis" not found'
location: <unknown location>:-1
`

**Comment by yanchxx** [comment]
> Hello，I have some question,I can not solve it. Can you help me? Thanks!!!
> 
> `Python: Traceback (most recent call last): File "/home/guo/Downloads/CharacterDriven-BlenderAddon-master (1)/CharacterDriven-BlenderAddon-master/blender/Beta.blend/Text", line 42, in modal File "/home/guo/Downloads/CharacterDriven-BlenderAddon-master (1)/CharacterDriven-BlenderAddon-master/blender/Beta.blend/Text", line 98, in process_poses KeyError: 'bpy_prop_collection[key]: key "Pelvis" not found' location: <unknown location>:-1 `

You should make Armature active,which means you have to select the Armature.
![image](https://user-images.githubusercontent.com/38496769/147027790-3dda0f86-56bb-448b-b664-96c4b645c61c.png)

**Comment by yanchxx** [comment]
> Hello，I have some question,I can not solve it. Can you help me? Thanks!!!
> 
> `Python: Traceback (most recent call last): File "/home/guo/Downloads/CharacterDriven-BlenderAddon-master (1)/CharacterDriven-BlenderAddon-master/blender/Beta.blend/Text", line 42, in modal File "/home/guo/Downloads/CharacterDriven-BlenderAddon-master (1)/CharacterDriven-BlenderAddon-master/blender/Beta.blend/Text", line 98, in process_poses KeyError: 'bpy_prop_collection[key]: key "Pelvis" not found' location: <unknown location>:-1 `

I fixed the bug, download the repo and try again.
