### ISSUE TITLE
Error in blender script

### ISSUE THREAD

**Issue by Harsh-Vavaiya** [yanchxx/CDBA#21]
![Screenshot (42)](https://user-images.githubusercontent.com/38744737/173187763-f8685d3c-3e34-49cf-a876-1b2e35701311.png)

@yanch2116  I've pressed Ctrl + E, after completing all frames, it's showing this error. Please help me here.

**Comment by yanchxx** [comment]
I can't see the picture

**Comment by Harsh-Vavaiya** [comment]
let me email you. what is your email id?

**Comment by yanchxx** [comment]
I see the picture now.

It seems the connection closed before the program close it, try to use `try` to catch the exception in the characterDriven.py line 42.
