### ISSUE TITLE
How to make the character move around origin point?

### ISSUE THREAD

**Issue by lucasjinreal** [yanchxx/CDBA#23]
currently seems the hips postion always to zero, how to make it move around origin point then it can looks more natural?

**Comment by yanchxx** [comment]
You can move Pelvis's postion, it's the root joint.

<img width="761" alt="image" src="https://user-images.githubusercontent.com/38496769/184619511-a9685853-1526-44ff-9715-112b4df94270.png">

Is the character's position right?

**Comment by lucasjinreal** [comment]
@yanch2116 Hi, I am using the cam_trans from ROMP output as transition. I applied 100*cam_trans convert it to cm unit.

But the character can not really saw move.  Do u have a video what's your motion looks like?

https://github.com/yanch2116/CDBA/blob/master/demo/demo1.gif

this demo you can clearly see the hips are fixed (even more obvious when character down and up)

**Comment by yanchxx** [comment]
I just use `bpy.data.objects['Armature'].pose.bones['Pelvis'].location` to change the hip's translation.

It's [here](https://github.com/yanch2116/CDBA/blob/master/addon/ops/animation.py#L43).
