### ISSUE TITLE
Detection variable: outputs = {'poses': poses, 'trans': trans[0]}

### ISSUE THREAD

**Issue by zhangby2085** [yanchxx/CDBA#27]
Hey, Yanchxx,

May I ask, what is the output variable, I think "trans" is the translation between camera and object.

What are the poses, is it the location x, y, z, or rotation x, y, z, degrees?

Thank you 👍

**Comment by yanchxx** [comment]
"trans" is the hip's position in the world coordinate
"poses" is joint's rotation in [axis-angle representation](https://en.wikipedia.org/wiki/Axis%E2%80%93angle_representation)

**Comment by zhangby2085** [comment]
Many thanks for the reply, it helps a lot, I try to get an overall point of view on how it works.

By the way, in the process of running romp, what is the key of params_pred, smpl_thetas, smpl_betas? unable to locate the documentation of them.

**Comment by yanchxx** [comment]
smpl_thetas, smpl_betas is the term used in paper [SMPL](https://dl.acm.org/doi/abs/10.1145/2816795.2818013)

ROMP is a frontier paper code implementation, you can consider to see the relevant knowledge of the paper, obviously there will not be a perfect manual for reference.

**Comment by foocker** [comment]
> 
will add more frontier paper  which based on SMPL on 3d human construction, such as [VIBE](https://github.com/mkocabas/VIBE)  ,[HybrIK](https://github.com/Jeff-sjtu/HybrIK) and so on. may there are some subtle difference?

**Comment by zhangby2085** [comment]
Excellent, great thanks for the effort, the paper and repos are nice to know, wanna extract the bones mapping (location and rotations), is there a way to get from romp?
![image](https://user-images.githubusercontent.com/40630354/191667236-faaf4cd9-ce51-405a-9de7-01973cca69f5.png)

**Comment by yanchxx** [comment]
Maybe this [file](https://github.com/yanchxx/CABA/blob/d3c4a9f461bffbfb75ec961ef219cc58fdca2563/romp_server.py) is helpful.
Look at this [function](https://github.com/yanchxx/CABA/blob/d3c4a9f461bffbfb75ec961ef219cc58fdca2563/romp_server.py#L58).

**Comment by yanchxx** [comment]
> > 
> 
> will add more frontier paper which based on SMPL on 3d human construction, such as [VIBE](https://github.com/mkocabas/VIBE) ,[HybrIK](https://github.com/Jeff-sjtu/HybrIK) and so on. may there are some subtle difference?

I don't know exactly what you mean? Do you want me to add a feature about VIBE?

**Comment by zhangby2085** [comment]
Hello again, and the recommendations are beneficial and helpful, and how about in Unity, I noticed that the difference between Blender and Unity is the axis angle rotations work straight away in Blender, and in Unity, it is differently allocated
![MicrosoftTeams-image](https://user-images.githubusercontent.com/40630354/191903815-d1ef775e-0d28-4f68-8e4c-617f1b0dc1d2.png)

**Comment by foocker** [comment]
> > > 
> > 
> > 
> > will add more frontier paper which based on SMPL on 3d human construction, such as [VIBE](https://github.com/mkocabas/VIBE) ,[HybrIK](https://github.com/Jeff-sjtu/HybrIK) and so on. may there are some subtle difference?
> 
> I don't know exactly what you mean? Do you want me to add a feature about VIBE?

api such as romp output, like vibe...you can choose use which model's output.  more api（interface）may can test more new paper's result ,can get better 3d pose infomation to driver.
your WOC will open? especial on MeshCNN to autorig.

**Comment by yanchxx** [comment]
> > > > 
> > > 
> > > 
> > > will add more frontier paper which based on SMPL on 3d human construction, such as [VIBE](https://github.com/mkocabas/VIBE) ,[HybrIK](https://github.com/Jeff-sjtu/HybrIK) and so on. may there are some subtle difference?
> > 
> > 
> > I don't know exactly what you mean? Do you want me to add a feature about VIBE?
> 
> api such as romp output, like vibe...you can choose use which model's output. more api（interface）may can test more new paper's result ,can get better 3d pose infomation to driver. your WOC will open? especial on MeshCNN to autorig.

WOC will not open because the company won't allow it. The auto-rig part needs improvement.

Thank you for your advice. I'll be adding some useful features to this repository over the next few years to help visualize more new paper's result.
