### ISSUE TITLE
Can't connect ROMP into addon

### ISSUE THREAD

**Issue by hasanleiva** [yanchxx/CDBA#28]
I use ROMP v1.1 on Windows machine.
But CDBA works with version 1.0 of ROMP
I read installation and using documentation of ROMP v1.0 but i can't figured out all
How can i use this addon properly?
I'm not good at programming i'm animator and interested in your project.
Can you write steps how to install and use ROMP with this addon,please?

![image](https://user-images.githubusercontent.com/49316907/192546129-28b0b0ed-2ad3-48cc-a64c-76e0fbd42882.png)

**Comment by yanchxx** [comment]
Have you tried to install [simple-romp](https://github.com/yanchxx/CDBA#for-simple-romp)?

**Comment by hasanleiva** [comment]
Here error log when i run command pip install --upgrade simple-romp



`$ pip install --upgrade simple-romp
Collecting simple-romp
  Using cached simple_romp-1.0.5.tar.gz (110 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error

  python setup.py egg_info did not run successfully.
  exit code: 1

  [87 lines of output]
  c:\users\xasan\appdata\local\programs\python\python39\lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\Xasan\AppData\Local\Temp\pip-install-43h6x7yi\simple-romp_001f2ad55d544fd49dc8aaf883107725\vis_human\sim3drender\lib\rasterize.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  Compiling vis_human/sim3drender/lib/rasterize.pyx because it depends on c:\users\xasan\appdata\local\programs\python\python39\lib\site-packages\Cython\Includes\libcpp\__init__.pxd.
  [1/1] Cythonizing vis_human/sim3drender/lib/rasterize.pyx
  c:\users\xasan\appdata\local\programs\python\python39\lib\site-packages\setuptools\installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
    warnings.warn(
    error: subprocess-exited-with-error

    python setup.py bdist_wheel did not run successfully.
    exit code: 1

    [39 lines of output]
    Partial import of lap during the build process.
    C:\Users\Xasan\AppData\Local\Temp\pip-wheel-_62blu56\lap_46106f30ec87414b85f662aa4507f904\setup.py:223: DeprecationWarning:

      `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
      of the deprecation of `distutils` itself. It will be removed for
      Python >= 3.12. For older Python versions it will remain present.
      It is recommended to use `setuptools < 60.0` for those Python versions.
      For more details, see:
        https://numpy.org/devdocs/reference/distutils_status_migration.html


      from numpy.distutils.core import setup
    Generating cython files
    running bdist_wheel
    running build
    running config_cc
    INFO: unifing config_cc, config, build_clib, build_ext, build commands --compiler options
    running config_fc
    INFO: unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
    running build_src
    INFO: build_src
    INFO: building extension "lap._lapjv" sources
    INFO: building data_files sources
    INFO: build_src: building npy-pkg config files
    c:\users\xasan\appdata\local\programs\python\python39\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running build_py
    creating build
    creating build\lib.win-amd64-cpython-39
    creating build\lib.win-amd64-cpython-39\lap
    copying lap\lapmod.py -> build\lib.win-amd64-cpython-39\lap
    copying lap\__init__.py -> build\lib.win-amd64-cpython-39\lap
    running build_ext
    INFO: No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    INFO: customize MSVCCompiler
    INFO: customize MSVCCompiler using build_ext
    INFO: CCompilerOpt.cc_test_flags[1073] : testing flags (/O2)
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    INFO: CCompilerOpt.cache_flush[857] : write cache to path -> C:\Users\Xasan\AppData\Local\Temp\pip-wheel-_62blu56\lap_46106f30ec87414b85f662aa4507f904\build\temp.win-amd64-cpython-39\Release\ccompiler_opt_cache_ext.py
    [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
    ERROR: Failed building wheel for lap
  ERROR: Failed to build one or more wheels
  Traceback (most recent call last):
    File "c:\users\xasan\appdata\local\programs\python\python39\lib\site-packages\setuptools\installer.py", line 82, in fetch_build_egg
      subprocess.check_call(cmd)
    File "c:\users\xasan\appdata\local\programs\python\python39\lib\subprocess.py", line 373, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['c:\\users\\xasan\\appdata\\local\\programs\\python\\python39\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\Xasan\\AppData\\Local\\Temp\\tmp236am3ua', '--quiet', 'lap']' returned non-zero exit status 1.

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\Xasan\AppData\Local\Temp\pip-install-43h6x7yi\simple-romp_001f2ad55d544fd49dc8aaf883107725\setup.py", line 17, in <module>
      setuptools.setup(
    File "c:\users\xasan\appdata\local\programs\python\python39\lib\site-packages\setuptools\__init__.py", line 86, in setup
      _install_setup_requires(attrs)
    File "c:\users\xasan\appdata\local\programs\python\python39\lib\site-packages\setuptools\__init__.py", line 80, in _install_setup_requires
      dist.fetch_build_eggs(dist.setup_requires)
    File "c:\users\xasan\appdata\local\programs\python\python39\lib\site-packages\setuptools\dist.py", line 875, in fetch_build_eggs
      resolved_dists = pkg_resources.working_set.resolve(
    File "c:\users\xasan\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\__init__.py", line 789, in resolve
      dist = best[req.key] = env.best_match(
    File "c:\users\xasan\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\__init__.py", line 1075, in best_match
      return self.obtain(req, installer)
    File "c:\users\xasan\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\__init__.py", line 1087, in obtain
      return installer(requirement)
    File "c:\users\xasan\appdata\local\programs\python\python39\lib\site-packages\setuptools\dist.py", line 945, in fetch_build_egg
      return fetch_build_egg(self, req)
    File "c:\users\xasan\appdata\local\programs\python\python39\lib\site-packages\setuptools\installer.py", line 84, in fetch_build_egg
      raise DistutilsError(str(e)) from e
  distutils.errors.DistutilsError: Command '['c:\\users\\xasan\\appdata\\local\\programs\\python\\python39\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\Xasan\\AppData\\Local\\Temp\\tmp236am3ua', '--quiet', 'lap']' returned non-zero exit status 1.
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
`

**Comment by yanchxx** [comment]
Sorry, try Googling the error message, or ask the author of ROMP. I only used `pip install --upgrade simple-romp` to install ROMP, and I couldn't solve the problem.

**Comment by zhanghongyong123456** [comment]
> Here error log when i run command pip install --upgrade simple-romp
> 
> `$ pip install --upgrade simple-romp Collecting simple-romp Using cached simple_romp-1.0.5.tar.gz (110 kB) Preparing metadata (setup.py): started Preparing metadata (setup.py): finished with status 'error' error: subprocess-exited-with-error
> 
> python setup.py egg_info did not run successfully. exit code: 1
> 
> [87 lines of output] c:\users\xasan\appdata\local\programs\python\python39\lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\Xasan\AppData\Local\Temp\pip-install-43h6x7yi\simple-romp_001f2ad55d544fd49dc8aaf883107725\vis_human\sim3drender\lib\rasterize.pyx tree = Parsing.p_module(s, pxd, full_module_name) Compiling vis_human/sim3drender/lib/rasterize.pyx because it depends on c:\users\xasan\appdata\local\programs\python\python39\lib\site-packages\Cython\Includes\libcpp__init__.pxd. [1/1] Cythonizing vis_human/sim3drender/lib/rasterize.pyx c:\users\xasan\appdata\local\programs\python\python39\lib\site-packages\setuptools\installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer. warnings.warn( error: subprocess-exited-with-error
> 
> ```
> python setup.py bdist_wheel did not run successfully.
> exit code: 1
> 
> [39 lines of output]
> Partial import of lap during the build process.
> C:\Users\Xasan\AppData\Local\Temp\pip-wheel-_62blu56\lap_46106f30ec87414b85f662aa4507f904\setup.py:223: DeprecationWarning:
> 
>   `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
>   of the deprecation of `distutils` itself. It will be removed for
>   Python >= 3.12. For older Python versions it will remain present.
>   It is recommended to use `setuptools < 60.0` for those Python versions.
>   For more details, see:
>     https://numpy.org/devdocs/reference/distutils_status_migration.html
> 
> 
>   from numpy.distutils.core import setup
> Generating cython files
> running bdist_wheel
> running build
> running config_cc
> INFO: unifing config_cc, config, build_clib, build_ext, build commands --compiler options
> running config_fc
> INFO: unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
> running build_src
> INFO: build_src
> INFO: building extension "lap._lapjv" sources
> INFO: building data_files sources
> INFO: build_src: building npy-pkg config files
> c:\users\xasan\appdata\local\programs\python\python39\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
>   warnings.warn(
> running build_py
> creating build
> creating build\lib.win-amd64-cpython-39
> creating build\lib.win-amd64-cpython-39\lap
> copying lap\lapmod.py -> build\lib.win-amd64-cpython-39\lap
> copying lap\__init__.py -> build\lib.win-amd64-cpython-39\lap
> running build_ext
> INFO: No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
> INFO: customize MSVCCompiler
> INFO: customize MSVCCompiler using build_ext
> INFO: CCompilerOpt.cc_test_flags[1073] : testing flags (/O2)
> error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
> INFO: CCompilerOpt.cache_flush[857] : write cache to path -> C:\Users\Xasan\AppData\Local\Temp\pip-wheel-_62blu56\lap_46106f30ec87414b85f662aa4507f904\build\temp.win-amd64-cpython-39\Release\ccompiler_opt_cache_ext.py
> [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.
> ERROR: Failed building wheel for lap
> ```
> 
> ERROR: Failed to build one or more wheels Traceback (most recent call last): File "c:\users\xasan\appdata\local\programs\python\python39\lib\site-packages\setuptools\installer.py", line 82, in fetch_build_egg subprocess.check_call(cmd) File "c:\users\xasan\appdata\local\programs\python\python39\lib\subprocess.py", line 373, in check_call raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '['c:\users\xasan\appdata\local\programs\python\python39\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\Users\Xasan\AppData\Local\Temp\tmp236am3ua', '--quiet', 'lap']' returned non-zero exit status 1.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "", line 2, in File "", line 34, in File "C:\Users\Xasan\AppData\Local\Temp\pip-install-43h6x7yi\simple-romp_001f2ad55d544fd49dc8aaf883107725\setup.py", line 17, in setuptools.setup( File "c:\users\xasan\appdata\local\programs\python\python39\lib\site-packages\setuptools__init__.py", line 86, in setup _install_setup_requires(attrs) File "c:\users\xasan\appdata\local\programs\python\python39\lib\site-packages\setuptools__init__.py", line 80, in _install_setup_requires dist.fetch_build_eggs(dist.setup_requires) File "c:\users\xasan\appdata\local\programs\python\python39\lib\site-packages\setuptools\dist.py", line 875, in fetch_build_eggs resolved_dists = pkg_resources.working_set.resolve( File "c:\users\xasan\appdata\local\programs\python\python39\lib\site-packages\pkg_resources__init__.py", line 789, in resolve dist = best[req.key] = env.best_match( File "c:\users\xasan\appdata\local\programs\python\python39\lib\site-packages\pkg_resources__init__.py", line 1075, in best_match return self.obtain(req, installer) File "c:\users\xasan\appdata\local\programs\python\python39\lib\site-packages\pkg_resources__init__.py", line 1087, in obtain return installer(requirement) File "c:\users\xasan\appdata\local\programs\python\python39\lib\site-packages\setuptools\dist.py", line 945, in fetch_build_egg return fetch_build_egg(self, req) File "c:\users\xasan\appdata\local\programs\python\python39\lib\site-packages\setuptools\installer.py", line 84, in fetch_build_egg raise DistutilsError(str(e)) from e distutils.errors.DistutilsError: Command '['c:\users\xasan\appdata\local\programs\python\python39\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\Users\Xasan\AppData\Local\Temp\tmp236am3ua', '--quiet', 'lap']' returned non-zero exit status 1. [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed
> 
> Encountered error while generating package metadata.
> 
> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip. hint: See above for details. `

i have same  error ,have you done this error?

**Comment by yanchxx** [comment]
I guess it has something to do with your version of python. Can you provide more details? This includes python versions, pip versions, installed dependencies, etc. 

The error message here is that lap cannot be installed, I suggest it is better to use the error message Google.

**Comment by zhanghongyong123456** [comment]
> I guess it has something to do with your version of python. Can you provide more details? This includes python versions, pip versions, installed dependencies, etc.
> 
> The error message here is that lap cannot be installed, I suggest it is better to use the error message Google.

是的，的确是lap安装错误，我blender  2.9   python 3.7   安装错误，换成  blender 3.4     python 3.10   还是报错 ，我后来在anaconda 下安装同样版本的python，然后安装lap，之后将lap库拷贝到 blender 3.4  python的site-packages下， pip 一遍就可以了，我觉得是 blender python 环境管理的问题，有些依赖环境不全，安装起来总是报错，这么做的后果就是，我的cv用不了：ImportError: DLL load failed while importing cv2: 找不到指定的模块。 我还在解决这个错误

**Comment by zhanghongyong123456** [comment]
> I guess it has something to do with your version of python. Can you provide more details? This includes python versions, pip versions, installed dependencies, etc.
> 
> The error message here is that lap cannot be installed, I suggest it is better to use the error message Google.
这是我的操作命令：
![image](https://user-images.githubusercontent.com/48466610/208218199-0936eabf-cc3d-406a-a4d8-82aacacd185c.png)

我在blender下面安装的 opencv库， 他不在我这个目录下 C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\site-packages，而是在C盘新建一个文件夹 C:\Users\A\AppData\Roaming\Python\Python310\site-packages，这是为什么

**Comment by zhanghongyong123456** [comment]
不使用blender  自带 python 环境，采用   anconda 创建的虚拟环境替代：
1.  找到   blender 自带python 环境 路径（默认：C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\bin），查看 python 版本（3.10.8）；
2. 在anconda下创建新的虚拟环境： conda create -n   blender3.4   python=3.10.8   （这里python 版本最好和 上面查看的版本名一致，其实不一致也是可以的）。
3. 修改 blender自带 python环境的文件夹（C:\Program Files\Blender Foundation\Blender 3.4\3.4），里面的python文件夹改名字，例如 __python,目的是防止blender 查找自带的python环境
4. 链接 自己在anconda下新建的虚拟环境的 blender3.4 ； 以管理员身份打开控制提示符：cd  到 blender自带 python环境的文件夹（C:\Program Files\Blender Foundation\Blender 3.4\3.4） 链接命令： Mklink  /j python  H:\Anaconda3\envs\blender3.4   ，这时blender 使用的pytho环境就是你新创建的虚拟环境。
5.激活anconda下的虚拟环境 conda activate blender3.4， 此刻随意安装自己想安装的库。

**Comment by yanchxx** [comment]
> > I guess it has something to do with your version of python. Can you provide more details? This includes python versions, pip versions, installed dependencies, etc.
> > The error message here is that lap cannot be installed, I suggest it is better to use the error message Google.
> 
> 是的，的确是lap安装错误，我blender 2.9 python 3.7 安装错误，换成 blender 3.4 python 3.10 还是报错 ，我后来在anaconda 下安装同样版本的python，然后安装lap，之后将lap库拷贝到 blender 3.4 python的site-packages下， pip 一遍就可以了，我觉得是 blender python 环境管理的问题，有些依赖环境不全，安装起来总是报错，这么做的后果就是，我的cv用不了：ImportError: DLL load failed while importing cv2: 找不到指定的模块。 我还在解决这个错误

simple_romp不需要安装在blender python里面，可以单独开一个conda环境



> > I guess it has something to do with your version of python. Can you provide more details? This includes python versions, pip versions, installed dependencies, etc.
> > The error message here is that lap cannot be installed, I suggest it is better to use the error message Google.
> > 这是我的操作命令：
> > ![image](https://user-images.githubusercontent.com/48466610/208218199-0936eabf-cc3d-406a-a4d8-82aacacd185c.png)
> 
> 我在blender下面安装的 opencv库， 他不在我这个目录下 C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\site-packages，而是在C盘新建一个文件夹 C:\Users\A\AppData\Roaming\Python\Python310\site-packages，这是为什么

./python -m pip list 查看一下pip的已安装软件，看看有没有安装在里面。反正明确运行的python是blender的python，保证pip是属于blender python的pip就行，应该没啥问题。



> 不使用blender 自带 python 环境，采用 anconda 创建的虚拟环境替代：
> 
> 1. 找到   blender 自带python 环境 路径（默认：C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\bin），查看 python 版本（3.10.8）；
> 2. 在anconda下创建新的虚拟环境： conda create -n   blender3.4   python=3.10.8   （这里python 版本最好和 上面查看的版本名一致，其实不一致也是可以的）。
> 3. 修改 blender自带 python环境的文件夹（C:\Program Files\Blender Foundation\Blender 3.4\3.4），里面的python文件夹改名字，例如 __python,目的是防止blender 查找自带的python环境
> 4. 链接 自己在anconda下新建的虚拟环境的 blender3.4 ； 以管理员身份打开控制提示符：cd  到 blender自带 python环境的文件夹（C:\Program Files\Blender Foundation\Blender 3.4\3.4） 链接命令： Mklink  /j python  H:\Anaconda3\envs\blender3.4   ，这时blender 使用的pytho环境就是你新创建的虚拟环境。
>    5.激活anconda下的虚拟环境 conda activate blender3.4， 此刻随意安装自己想安装的库。

嗯，这是个不错的方案。

我readme没讲清楚，所以让你们以为simple_romp也安装在blender python里面了，如果是单独的conda环境的话，simple_romp应该是比较好安装的，只有opencv是需要安装在blender中的。

感谢你的反馈。

**Comment by yanchxx** [comment]
> Here error log when i run command pip install --upgrade simple-romp
> 
> `$ pip install --upgrade simple-romp Collecting simple-romp Using cached simple_romp-1.0.5.tar.gz (110 kB) Preparing metadata (setup.py): started Preparing metadata (setup.py): finished with status 'error' error: subprocess-exited-with-error
> 
> python setup.py egg_info did not run successfully. exit code: 1
> 
> [87 lines of output] c:\users\xasan\appdata\local\programs\python\python39\lib\site-packages\Cython\Compiler\Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: C:\Users\Xasan\AppData\Local\Temp\pip-install-43h6x7yi\simple-romp_001f2ad55d544fd49dc8aaf883107725\vis_human\sim3drender\lib\rasterize.pyx tree = Parsing.p_module(s, pxd, full_module_name) Compiling vis_human/sim3drender/lib/rasterize.pyx because it depends on c:\users\xasan\appdata\local\programs\python\python39\lib\site-packages\Cython\Includes\libcpp__init__.pxd. [1/1] Cythonizing vis_human/sim3drender/lib/rasterize.pyx c:\users\xasan\appdata\local\programs\python\python39\lib\site-packages\setuptools\installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer. warnings.warn( error: subprocess-exited-with-error
> 
> ```
> python setup.py bdist_wheel did not run successfully.
> exit code: 1
> 
> [39 lines of output]
> Partial import of lap during the build process.
> C:\Users\Xasan\AppData\Local\Temp\pip-wheel-_62blu56\lap_46106f30ec87414b85f662aa4507f904\setup.py:223: DeprecationWarning:
> 
>   `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
>   of the deprecation of `distutils` itself. It will be removed for
>   Python >= 3.12. For older Python versions it will remain present.
>   It is recommended to use `setuptools < 60.0` for those Python versions.
>   For more details, see:
>     https://numpy.org/devdocs/reference/distutils_status_migration.html
> 
> 
>   from numpy.distutils.core import setup
> Generating cython files
> running bdist_wheel
> running build
> running config_cc
> INFO: unifing config_cc, config, build_clib, build_ext, build commands --compiler options
> running config_fc
> INFO: unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
> running build_src
> INFO: build_src
> INFO: building extension "lap._lapjv" sources
> INFO: building data_files sources
> INFO: build_src: building npy-pkg config files
> c:\users\xasan\appdata\local\programs\python\python39\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
>   warnings.warn(
> running build_py
> creating build
> creating build\lib.win-amd64-cpython-39
> creating build\lib.win-amd64-cpython-39\lap
> copying lap\lapmod.py -> build\lib.win-amd64-cpython-39\lap
> copying lap\__init__.py -> build\lib.win-amd64-cpython-39\lap
> running build_ext
> INFO: No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
> INFO: customize MSVCCompiler
> INFO: customize MSVCCompiler using build_ext
> INFO: CCompilerOpt.cc_test_flags[1073] : testing flags (/O2)
> error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
> INFO: CCompilerOpt.cache_flush[857] : write cache to path -> C:\Users\Xasan\AppData\Local\Temp\pip-wheel-_62blu56\lap_46106f30ec87414b85f662aa4507f904\build\temp.win-amd64-cpython-39\Release\ccompiler_opt_cache_ext.py
> [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.
> ERROR: Failed building wheel for lap
> ```
> 
> ERROR: Failed to build one or more wheels Traceback (most recent call last): File "c:\users\xasan\appdata\local\programs\python\python39\lib\site-packages\setuptools\installer.py", line 82, in fetch_build_egg subprocess.check_call(cmd) File "c:\users\xasan\appdata\local\programs\python\python39\lib\subprocess.py", line 373, in check_call raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '['c:\users\xasan\appdata\local\programs\python\python39\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\Users\Xasan\AppData\Local\Temp\tmp236am3ua', '--quiet', 'lap']' returned non-zero exit status 1.
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last): File "", line 2, in File "", line 34, in File "C:\Users\Xasan\AppData\Local\Temp\pip-install-43h6x7yi\simple-romp_001f2ad55d544fd49dc8aaf883107725\setup.py", line 17, in setuptools.setup( File "c:\users\xasan\appdata\local\programs\python\python39\lib\site-packages\setuptools__init__.py", line 86, in setup _install_setup_requires(attrs) File "c:\users\xasan\appdata\local\programs\python\python39\lib\site-packages\setuptools__init__.py", line 80, in _install_setup_requires dist.fetch_build_eggs(dist.setup_requires) File "c:\users\xasan\appdata\local\programs\python\python39\lib\site-packages\setuptools\dist.py", line 875, in fetch_build_eggs resolved_dists = pkg_resources.working_set.resolve( File "c:\users\xasan\appdata\local\programs\python\python39\lib\site-packages\pkg_resources__init__.py", line 789, in resolve dist = best[req.key] = env.best_match( File "c:\users\xasan\appdata\local\programs\python\python39\lib\site-packages\pkg_resources__init__.py", line 1075, in best_match return self.obtain(req, installer) File "c:\users\xasan\appdata\local\programs\python\python39\lib\site-packages\pkg_resources__init__.py", line 1087, in obtain return installer(requirement) File "c:\users\xasan\appdata\local\programs\python\python39\lib\site-packages\setuptools\dist.py", line 945, in fetch_build_egg return fetch_build_egg(self, req) File "c:\users\xasan\appdata\local\programs\python\python39\lib\site-packages\setuptools\installer.py", line 84, in fetch_build_egg raise DistutilsError(str(e)) from e distutils.errors.DistutilsError: Command '['c:\users\xasan\appdata\local\programs\python\python39\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\Users\Xasan\AppData\Local\Temp\tmp236am3ua', '--quiet', 'lap']' returned non-zero exit status 1. [end of output]
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed
> 
> Encountered error while generating package metadata.
> 
> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip. hint: See above for details. `

simple_romp is installed in a separate conda environment, only opencv needs to be installed in blender python. @hasanleiva

**Comment by zhanghongyong123456** [comment]
> > > 我想这与您的python版本有关。你能提供更多细节吗？这里包括python版本，pip版本，安装的依赖等
> > > ，这里的报错信息是无法安装lap，我建议还是用报错信息谷歌比较好。
> > 
> > 
> > 是的，的确是lap安装错误，我blender 2.9 python 3.7 安装错误，换成 blender 3.4 python 3.10 还是报错 ，我后来在anaconda 下安装同样版本的python，然后安装lap，之后将lap库拷贝到 blender 3.4 python的site-packages下， pip 一遍就可以了，我觉得是 blender python 环境管理的问题，有些依赖环境不全，安装起来总是报错，这么做的后果就是，我的cv用不了：ImportError: DLL load failed while importing cv2: 找不到指定的模块。 我还在解决这个错误
> 
> simple_romp不需要安装在blender python里面，可以单独开一个conda环境
> 
> > > 我想这与您的python版本有关。你能提供更多细节吗？这里包括python版本，pip版本，安装的依赖等
> > > 。这里的报错信息是无法安装lap，我建议还是用报错信息谷歌比较好。
> > > 这是我的操作命令：
> > > ![图片](https://user-images.githubusercontent.com/48466610/208218199-0936eabf-cc3d-406a-a4d8-82aacacd185c.png)
> > 
> > 
> > 我在blender下面安装的 opencv库， 他不在我这个目录下 C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\site-packages，而是在C盘新建一个文件夹 C:\Users\A\AppData\Roaming\Python\Python310\site-packages，这是为什么
> 
> ./python -m pip list 查看一下pip的已安装软件，看看有没有安装在里面。反正明确运行的python是blender的python，保证pip是属于blender python的pip就行，应该没啥问题。
> 
> > 不使用blender 自带 python 环境，采用 anconda 创建的虚拟环境替代：
> > 
> > 1. 找到   blender 自带python 环境 路径（默认：C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\bin），查看 python 版本（3.10.8）；
> > 2. 在anconda下创建新的虚拟环境： conda create -n   blender3.4   python=3.10.8   （这里python 版本最好和 上面查看的版本名一致，其实不一致也是可以的）。
> > 3. 修改 blender自带 python环境的文件夹（C:\Program Files\Blender Foundation\Blender 3.4\3.4），里面的python文件夹改名字，例如 __python,目的是防止blender 查找自带的python环境
> > 4. 链接 自己在anconda下新建的虚拟环境的 blender3.4 ； 以管理员身份打开控制提示符：cd  到 blender自带 python环境的文件夹（C:\Program Files\Blender Foundation\Blender 3.4\3.4） 链接命令： Mklink  /j python  H:\Anaconda3\envs\blender3.4   ，这时blender 使用的pytho环境就是你新创建的虚拟环境。
> >    5.激活anconda下的虚拟环境 conda activate blender3.4， 此刻随意安装自己想安装的库。
> 
> 嗯，这是个不错的方案。
> 
> 我readme没讲清楚，所以让你们以为simple_romp也安装在blender python里面了，如果是单独的conda环境的话，simple_romp应该是比较好安装的，只有opencv是需要安装在blender中的。
> 
> 感谢你的反馈。

我的这个操作直接把blender 自带的python环境替换了，不使用blender自带的环境，自己在anconda 新建一个虚拟环境替代了，所有库安装和使用与blender自带的python环境一点关系没有，后续在blender里面的运行环境也是新的虚拟环境，而非本身自带的环境。
