### ISSUE TITLE
导入fbx时骨骼方向乱了

### ISSUE THREAD

**Issue by syguan96** [yanchxx/CDBA#3]
@yanch2116 你好，非常酷的工作！我基本把整个项目跑通了，但我有两个问题想进一步请教一下你。　、
１．导入fbx时骨骼的方向错乱了，参见:https://www.bilibili.com/read/cv2520452 。但是这个文章里的方法没有完全解决方向错乱的问题，所以我想请问一下你，你是怎么解决这个问题的呢？
２．我想请教一下，如何将编辑骨架让其和ｓｍｐｌ的骨架一致呢？
望不吝赐教！万分感谢！

**Comment by yanchxx** [comment]
第一个问题理论上编写插件可以解决吧，对所有骨骼进行一个整体的方向转换。
第二个问题比较难解决，应该是从一开始进行骨骼绑定的时候，就确定好根骨头、骨头数量、骨头之间的父子关系和SMPL的骨架完全一致（初始姿态也要尽可能保持一致），然后再刷蒙皮权重。我也是偶然发现从mixamo下载的这个3D人物是与SMPL的骨架完全一致的，无需再手动进行修改。
第二个问题实际上也是我在研究的一个问题，如何为用户已有的3D模型绑定一套SMPL骨骼，从而能用ROMP直接驱动，目前进展甚微。
总的来说，这个插件目前只能用来为一些基于SMPL的3D姿态估计模型做个简单的展示，如果想用你自己的3D人物，需要大量的人工操作。

**Comment by syguan96** [comment]
你导入这个模型的时候有发现骨骼方向错乱的问题吗

**Comment by yanchxx** [comment]
你是说mixamo的这个3D人物吗，这样算错乱吗
![image](https://user-images.githubusercontent.com/38496769/147230746-e55dcf72-1015-4b42-a530-1e28b198dd79.png)
![image](https://user-images.githubusercontent.com/38496769/147230867-ddd0a770-b5cb-45f7-b92b-0f37a6ed7a13.png)

**Comment by syguan96** [comment]
是的是的，第一张图里那样，我看你提供的blend里没有这种情况，所以想问一下你是怎么弄的

**Comment by yanchxx** [comment]
这好像不是错乱，是正常的，我只是在我的blend中将骨架图层隐藏了
![image](https://user-images.githubusercontent.com/38496769/147235351-349ac03b-5d17-4658-b49a-b0f17500fac6.png)

**Comment by syguan96** [comment]
奥，I see, 但是用maya导入就是正常的，网上说会对骨骼动画有一些影响

**Comment by yanchxx** [comment]
感觉影响应该不大，因为LBS只需要关节点位置（就是骨头的head的位置）和骨头长度就行，具体骨头的tail在哪里应该不影响。

**Comment by syguan96** [comment]
恩恩，非常感谢你的帮助！　谢谢！
