### ISSUE TITLE
Where is Panel?

### ISSUE THREAD

**Issue by caihaunqai** [yanchxx/CDBA#30]
Hello, Thank you for your great job. I am not familiar with blender. Can you help me? I can not find the Panel. Thank you.
![image](https://user-images.githubusercontent.com/56779804/204522353-10e26494-9d10-45af-a591-be929a994ea0.png)

**Comment by yanchxx** [comment]
After install the blender addon, you can press N to toggle the panel.

<img width="752" alt="image" src="https://user-images.githubusercontent.com/38496769/204955125-0984e19c-2a33-4acd-b989-5e4c61264606.png">
