### ISSUE TITLE
AttributeError: 'Mesh' object has no attribute 'edit_bones'

### ISSUE THREAD

**Issue by Yuanhong200727** [yanchxx/CDBA#32]
您好！
当我导入自己的已经绑定好骨骼的标准的smpl模型，并点击fix bones时出现了下面的报错：
![123](https://user-images.githubusercontent.com/117512740/209678317-4da655be-129c-4536-bae2-4a3f384d745f.jpg)
请问这是什么原因呢？
感谢！

**Comment by yanchxx** [comment]
人物和骨架反了，应该character是skeleton，骨架是T-pose
