### ISSUE TITLE
求教

### ISSUE THREAD

**Issue by zcdliuwei** [yanchxx/CDBA#35]
大佬您好，看了你这个项目很受震惊，因为让一个动漫角色跳舞，是我一直想做但是没有实现思路的地方。
我没有用过Blender，对她不熟悉，所以有个问题想问一下，假设我有一个动漫角色了，比如龙珠里面的孙悟空，obj或者其他的3D格式，然后我想用B站或者油管的跳舞视频进行驱动，让孙悟空跳舞，得到一个GIF或者MP4文件
因为我不用Blender，所以不能使用您的插件，请问实现上述目标的代码在哪里，可以参考一下吗
请原谅我幼稚的问题，期待您的解惑！

**Comment by yanchxx** [comment]
整体流程为

- 使用3D姿态估计模型（如[ROMP](https://github.com/Arthur151/ROMP))从图像或视频中获取人物的3D姿态
- 利用3D姿态进行[骨骼动画](https://en.wikipedia.org/wiki/Skeletal_animation)，3D姿态用于驱动骨骼，然后骨骼驱动3D人物，在blender中只需要[传入3D姿态](https://github.com/yanchxx/CDBA/blob/master/addon/ops/animation.py#L53)，就能够自动进行骨骼动画

**Comment by zcdliuwei** [comment]
> 整体流程为
> 
> * 使用3D姿态估计模型（如[ROMP](https://github.com/Arthur151/ROMP))从图像或视频中获取人物的3D姿态
> * 利用3D姿态进行[骨骼动画](https://en.wikipedia.org/wiki/Skeletal_animation)，3D姿态用于驱动骨骼，然后骨骼驱动3D人物，在blender中只需要[传入3D姿态](https://github.com/yanchxx/CDBA/blob/master/addon/ops/animation.py#L53)，就能够自动进行骨骼动画

我想把它做成一个全自动的pipeline，不需要借助Blender等软件，只需要输入3D人物，以及一段自己喜欢的跳舞视频，让程序直接生成3D人物跳舞的动图或视频，现在就是不知道，怎么才能不依赖Blender实现这一点

**Comment by yanchxx** [comment]
> > 整体流程为
> > 
> > * 使用3D姿态估计模型（如[ROMP](https://github.com/Arthur151/ROMP))从图像或视频中获取人物的3D姿态
> > * 利用3D姿态进行[骨骼动画](https://en.wikipedia.org/wiki/Skeletal_animation)，3D姿态用于驱动骨骼，然后骨骼驱动3D人物，在blender中只需要[传入3D姿态](https://github.com/yanchxx/CDBA/blob/master/addon/ops/animation.py#L53)，就能够自动进行骨骼动画
> 
> 我想把它做成一个全自动的pipeline，不需要借助Blender等软件，只需要输入3D人物，以及一段自己喜欢的跳舞视频，让程序直接生成3D人物跳舞的动图或视频，现在就是不知道，怎么才能不依赖Blender实现这一点

视频->ROMP->3D Pose->骨骼前向运动学->骨骼动画LBS算法->可视化渲染（Python的3D库）->视频，只能说难度不小

如果借助blender python的话倒是还好，设定好一个固定的场景，然后在命令行进行blender渲染，全程就是命令行输入输出，我之前弄过，但是意义不大，因为单目的驱动效果并不会很好，还需要在3D软件中修改，所以用blender是最合理的

当然，借助blender python也需要安装blender，还需要一些设置，你这么一说我突然感觉好像确实又有一点点价值，下次放出来吧

**Comment by yanchxx** [comment]
哦对了，这样固定某个人物还好，想要能够输入自定义人物，这个难度确实就不小了，而且效果不会很好

**Comment by zcdliuwei** [comment]
> 

大佬能不能把这个放出来 ？
我想接着您的工作继续往下探索一番，这是我想实现的东西。我虽然习惯使用Python，但对Blender不熟，更重要的是，这是我第一次接触3D领域，对骨骼动画啥的完全不了解，我是一个图像算法，之前都是研究2D图像。之前的想法，是在纯2D领域，通过motion transfer和pose transfer来实现动漫角色跳舞，就是从跳舞视频的每一帧上，抽取pose，再通过pose改变动漫角色的动作，然后把每一帧串起来做成视频，遇到的问题是：一是现在的motion transfer都是在真人上做的，需要针对动漫人物单独训练模型，二是运动和姿态迁移的时候，动漫人物的衣服等不会迁的很好，视频会有明显的伪影和不自然的地方
后来就想着在3D上尝试，确实看到了像ROMP类似的很多模型可以在image或者video上抽取3D pose，但是怎么指导动漫人物做出指定动作我就不懂了，所以现在进退两难
希望大佬考虑一下，是否可以把您之前的工作放出来，我尝试着往下做

**Comment by yanchxx** [comment]
过几天整理一下放出来，正好准备写毕设

**Comment by zcdliuwei** [comment]
> 过几天整理一下放出来，正好准备写毕设

谢谢大佬了，我先去把我们上面讨论的内容再梳理一下，同时准备一下骨骼动画方面的知识。
下周我再从这里联系您，或者不介意的话，加个微信方便沟通，我的是：zcdliuwei（浙江财经大学刘伟的简写哈哈）

**Comment by zcdliuwei** [comment]
我现在也在关注下面这两个方法（3D的pose迁移、从视频中重构3D对象等）
![image](https://user-images.githubusercontent.com/36565076/227118900-60722969-a7b0-4614-8914-169608eced9e.png)
![hybrik_dance](https://user-images.githubusercontent.com/36565076/227119190-7a98d978-9793-47e1-866b-e53a3d16104c.gif)
自从去年由扩散模型，以及今年ChatGPT主导的AIGC大火之后，也有人通过扩散模型在3D领域做出很好的成果，甚至达到state-of-the-art

**Comment by yanchxx** [comment]
看上去确实效果不错的，不过我没跟这方面，我就一开发😂

**Comment by zcdliuwei** [comment]
> 看上去确实效果不错的，不过我没跟这方面，我就一开发😂

那些成果我是这几天搜索文献的时候找到的，还没看具体思路，3D重构，怎么带着动漫人物的衣服等，我不知道，或许有直接带着衣服重构、渲染的方法，再找找吧
期待您的工作放出来，我等着啦

**Comment by yanchxx** [comment]
据我之前看的一篇论文，这些都是神经网络的方法，我这个就是比较传统的骨骼动画，方向不一样，搞开发弄着玩玩可以，搞科研没啥前途，卷那些神经网络方法比较好

**Comment by zcdliuwei** [comment]
> 据我之前看的一篇论文，这些都是神经网络的方法，我这个就是比较传统的骨骼动画，方向不一样，搞开发弄着玩玩可以，搞科研没啥前途，卷那些神经网络方法比较好

       我就是研究神经网络的，神经网络确实强大，但是需要大量的数据和算力支撑，所以我们用的都是开源的预训练模型，拿大厂训练好的模型直接用，或者在我们自己的小数据集上微调一下。
       我觉得还是任务驱动，如果有不需要训练模型的、偏传统一点的方法，同时可以达到效果的话，就不必执着于神经网络。我之前想着在2D上做动漫人物跳舞，就是发现需要针对动漫人物单独训练模型，而现在又不具备训练条件，才想着去3D上试试，因为感觉3D上似乎有方法，不需要区分真人还是动漫，可以直接做pose迁移，然后找来找去，就找到您的实现了，跟我想象中的一样，只不过希望不依赖Blender。目前您的方法就这一个限制，是最接近期望目标的实现，所以对您的方法最期待

**Comment by iAiuzjh** [comment]
想问问两位的工作进行到什么程度了呢，我们小组的节课项目的一个部分也想要实现一个类似的pipline，想知道能否借鉴一下
