### ISSUE TITLE
fix bones运行出错

### ISSUE THREAD

**Issue by 1679712850** [yanchxx/CDBA#37]
您好！当我导入mixamo模型，然后点击fix bones，总会报如下错误，请问您应该如何解决
<img width="1280" alt="uTools_1685094470971" src="https://github.com/yanchxx/MoPA/assets/94947323/daaf63f2-5cec-465c-9308-431e5f01d8d1">

**Comment by yanchxx** [comment]
骨架那里也改成metarig

**Comment by 1679712850** [comment]
您好，更改后，还是会出现问题
<img width="1280" alt="uTools_1685099468886" src="https://github.com/yanchxx/MoPA/assets/94947323/ad88000c-0513-4aca-bef4-e4f361643d57">

**Comment by yanchxx** [comment]
这里就是少了个骨头，你这个是mixamo绑定的吗，能看看是哪个模型吗
