### ISSUE TITLE
fixbone

### ISSUE THREAD

**Issue by LihaoshengQAZ** [yanchxx/CDBA#38]

**Comment by LihaoshengQAZ** [comment]
你好，我现在有一个obj格式的外观模型，然后去mixamo绑定过骨骼之后但是fixbone会出现人物骨骼位置错误导致驱动非常不精准（比如一开始人的手就是水平伸直朝背后）的情况。您有遇到吗？这个应该怎么解决掉呢？

**Comment by yanchxx** [comment]
有图看看吗？你是驱动后还不准吗？还是一开始的姿势不准？

**Comment by LihaoshengQAZ** [comment]
就比如这个，一开始绑定骨骼之后手臂就会有弯曲
<img width="303" alt="image" src="https://github.com/yanchxx/MoPA/assets/107200918/e7104c7b-210d-4ef6-9e84-56223af869b4">
然后驱动的时候就会一直处于弯曲状态（这本应该是直着身子行走）
<img width="255" alt="image" src="https://github.com/yanchxx/MoPA/assets/107200918/70652ead-77f2-462c-a052-3acd477e1fad">

**Comment by yanchxx** [comment]
<img width="817" alt="image" src="https://github.com/yanchxx/MoPA/assets/38496769/c3e64bb0-1137-4809-a364-f29723f54f8d">

这步弄了吗

**Comment by LihaoshengQAZ** [comment]
我尝试了，但是因为这个非常难以调整手臂的位置，导致效果更加的变差，所以我就没有应用

**Comment by LihaoshengQAZ** [comment]
就是挥手的动作就变成这个样子了
<img width="284" alt="image" src="https://github.com/yanchxx/MoPA/assets/107200918/336244a0-51de-4057-9cb4-8110216a58ce">

**Comment by yanchxx** [comment]
你一开始的obj是啥姿势的？顺便看一下你edit mode模式下绑定好的模型姿态。

**Comment by yanchxx** [comment]
反正不管咋样，在edit mode下都需要把骨骼弄成标准的T-pose，也不需要手动，我稍微问了下gpt，你可以参考参考。
<img width="510" alt="image" src="https://github.com/yanchxx/MoPA/assets/38496769/56ff427b-ef79-4481-810a-32708f063fc8">

**Comment by LihaoshengQAZ** [comment]
好的，非常感谢！

**Comment by yanchxx** [comment]
今天仔细看了一下，在pose模式下通过改变骨骼的位置和旋转角应该能轻松点把模型摆成T-pose，然后再用cats插件把pose下的模型弄到edit模式下，最后再fixBones一下。不过如果手是弯曲的，感觉直接调参数确实不太行，用代码调T-pose确实是不太好弄。

我感觉绑定的时候最好就能用T-pose或者A-pose的模型，mixamo调整T-pose应该仅仅是把旋转角改变了一下，没有改变骨头的位置，所以没法把整个模型放到一个平面上。

**Comment by ZongguoMo** [comment]
> 你好，我现在有一个obj格式的外观模型，然后去mixamo绑定过骨骼之后但是fixbone会出现人物骨骼位置错误导致驱动非常不精准（比如一开始人的手就是水平伸直朝背后）的情况。您有遇到吗？这个应该怎么解决掉呢？

你好，我也是obj格式的mesh模型，在mixamo绑定后，点击fixbone,只看到骨架，没有看到obj外观，应该是骨架太大了，把obj覆盖了，然后点击运行，只看到一小团东西在动，看不清楚，应该是骨架在动，请问你遇到这个问题吗？

**Comment by LihaoshengQAZ** [comment]
> 

我遇到了，但是也不知道为什么，还没有解决
