### ISSUE TITLE
驱动自己的模型

### ISSUE THREAD

**Issue by ZongguoMo** [yanchxx/CDBA#39]
您好大佬，我跑通了你的这个 demo，在 mixamo 上下载的3d 角色模型也能跑通，我现在用 SMPL 模型（T-pose）的 obj 格式 mesh 网格去 mixamo 绑定骨骼,保存位 T-pose 的 fbx 格式（图 1是pose模式下的样子），但是在点击 fixbone 后，模型变成下图 2 这样，然后
   也能运行，骨架是错乱的，老哥可以给点建议吗？感激不尽。
![1](https://github.com/yanchxx/MoPA/assets/71313548/cbccf160-aa9b-4c68-8461-ec16196b500a)
![2](https://github.com/yanchxx/MoPA/assets/71313548/95be66e4-6173-44b9-98b0-a67ba2c27048)

**Comment by yanchxx** [comment]
把骨骼隐藏了就看不到骨骼了，点Armature旁边那个小眼睛

不过我会改一下FixBones，根据它的长度去调整它的方位，之前都是直接加了2m，有些骨骼就有点太长了

**Comment by Robin-Mo** [comment]
感谢老哥回复，我把加2换成了0.006，没有出现骨架包裹模型的情况了，程序能够运行，但是我的模型因为坐标非常小，只有mixamo上的差不多十分之一，关节点的长度很小，所以运行的时候根本看不见模型运动，我现在想把模型放大，但是坐标没有变大，还是很小，这个怎么解决呢，考虑模型坐标变大，还是说从drivechacter函数调小转输的坐标呢

**Comment by ZongguoMo** [comment]
> 把骨骼隐藏了就看不到骨骼了，点Armature旁边那个小眼睛
> 
> 不过我会改一下FixBones，根据它的长度去调整它的方位，之前都是直接加了2m，有些骨骼就有点太长了
感谢老哥回复，我把加2换成了0.006，没有出现骨架包裹模型的情况了，程序能够运行，但是我的模型因为坐标非常小，只有mixamo上的差不多十分之一，关节点的长度很小，所以运行的时候根本看不见模型运动，我现在想把模型放大，但是坐标没有变大，还是很小，这个怎么解决呢，考虑模型坐标变大，还是说从drivechacter函数调小转输的坐标呢

**Comment by yanchxx** [comment]
嗯，在drivecharacter里面调整translation的尺度就行了

**Comment by ZongguoMo** [comment]
> 嗯，在drivecharacter里面调整translation的尺度就行了

改好了，非常感谢大佬指点，收下我的膝盖
