### ISSUE TITLE
插件导入问题

### ISSUE THREAD

**Issue by hhhlllyyy** [yanchxx/CDBA#4]
![7b9260e25369636c9c3bca4009e8964](https://user-images.githubusercontent.com/79896898/147654285-3d31dbbf-174f-418c-aef1-626196c0b84f.png)
![d3f0fd46a7730f58b61c3005858b37a](https://user-images.githubusercontent.com/79896898/147654295-5bdc7d8a-595c-4083-b6a9-0929e61b74f8.png)
您好感谢您开发的插件，对blender不是很熟悉，我添加了插件但却没有出现在列表里面，这是正常的吗？

![141be66e5a767c4792e6324eefae750](https://user-images.githubusercontent.com/79896898/147654398-1dd1dcc2-0b77-4120-a91c-4e9650d3117c.png)
![8d54144f47f01342acc59c27439095f](https://user-images.githubusercontent.com/79896898/147654406-c5269652-8003-40d3-aa6d-cb59908e7c7e.png)
在打开模型后执行ROMP中的 webcam_blender.sh一直停在这个界面，好像没有request请求，ctrl+e也没有反应，请问要如何解决呢？

**Comment by yanchxx** [comment]
> ![7b9260e25369636c9c3bca4009e8964](https://user-images.githubusercontent.com/79896898/147654285-3d31dbbf-174f-418c-aef1-626196c0b84f.png) ![d3f0fd46a7730f58b61c3005858b37a](https://user-images.githubusercontent.com/79896898/147654295-5bdc7d8a-595c-4083-b6a9-0929e61b74f8.png) 您好感谢您开发的插件，对blender不是很熟悉，我添加了插件但却没有出现在列表里面，这是正常的吗？
> 
> ![141be66e5a767c4792e6324eefae750](https://user-images.githubusercontent.com/79896898/147654398-1dd1dcc2-0b77-4120-a91c-4e9650d3117c.png) ![8d54144f47f01342acc59c27439095f](https://user-images.githubusercontent.com/79896898/147654406-c5269652-8003-40d3-aa6d-cb59908e7c7e.png) 在打开模型后执行ROMP中的 webcam_blender.sh一直停在这个界面，好像没有request请求，ctrl+e也没有反应，请问要如何解决呢？

更新了一个中文版的readme，按照步骤去试一试吧～

**Comment by hhhlllyyy** [comment]
好的非常感谢！问题已解决！

**Comment by zhLawliet** [comment]
@yanchxx 
 请问一下，上面提到的“一个中文版的readme”在哪？
卡在“Install the addon in Blender.”了
