### ISSUE TITLE
where did u download the background?

### ISSUE THREAD

**Issue by lucasjinreal** [yanchxx/CDBA#5]
where did u download the background?

**Comment by yanchxx** [comment]
The image background is from Google Images.
The video background is downloaded from BiliBili.

**Comment by lucasjinreal** [comment]
@yanch2116 Do u know how to insert video background to blender?

**Comment by yanchxx** [comment]
渲染动画时添加视频背景只需要按照Readme中的Background的进行操作就可以，渲染出来的动画就是有视频背景的了。
如果想在Blender中就看到视频背景，按照下图操作，添加视频路径即可。
![image](https://user-images.githubusercontent.com/38496769/147942474-936460d8-1e42-497e-a64f-93d91846fa5a.png)

**Comment by lucasjinreal** [comment]
@yanch2116 我在播放默认的那个跳舞动画的时候，即使是30fps，看着也有点卡，是为啥呀，是因为检测的姿态抖动导致的吗

**Comment by yanchxx** [comment]
在Blender中实时播放的效果肯定不如渲染出视频的效果，人物看上去都会有点模糊，不渲染Texture的话就还行，渲染了Texture就会看上去卡卡的
