### ISSUE TITLE
how to move the charactor to the ground?

### ISSUE THREAD

**Issue by lucasjinreal** [yanchxx/CDBA#6]
![image](https://user-images.githubusercontent.com/21303438/147941691-d5df9b2f-cd5a-40a4-b874-fd21008af621.png)

it now parallel with ground?

**Comment by yanchxx** [comment]
如果有小键盘的话，按小键盘的0进入摄像机视角，那是我调好的视角，姿势传输进去、渲染动画都是用这个视角的。你这个情况就是退出了摄像机视角，一般稍微移动下鼠标就会这样。
如果没有小键盘的话，按照下图操作，从edit进入preference，然后设置input里的Emulate Numpad，即可让顶部的数字键变成小键盘的数字键，再按0就行。
![image](https://user-images.githubusercontent.com/38496769/147942851-e16d6542-4bb4-4cfe-9dd1-45df5360cddd.png)

**Comment by lucasjinreal** [comment]
@yanch2116 Hi, thanks for your explaination. I can using mouse middle button switch the view, but I want to know, how to change the camera position to view person on the ground, since I want add a 3d ground surface at the bottom of model.

就是说，让人看起来是站在3d的地面上跳舞的那种感觉，这个时候人的原点是和地面平行的就看着很别扭

**Comment by yanchxx** [comment]
看这个[Blender教程](https://www.bilibili.com/video/BV1zh411Y7LX?from=search&seid=17419256116136872053&spm_id_from=333.337.0.0)的第零章，就能学会如何改变模型的位置以及如何设置摄像机视角了
