### ISSUE TITLE
运行插件时报错

### ISSUE THREAD

**Issue by jason870509** [yanchxx/CDBA#7]
首先感谢您分享这个插件，有个问题希望能帮忙解决
我在运行插件时报错，按space没有产生动作，无法解决，请问是什么原因，谢谢
![image](https://user-images.githubusercontent.com/42599221/148211612-fbc22c92-4a21-4a7a-ac00-737dad44fdb1.png)
传送是有跑完的
![image](https://user-images.githubusercontent.com/42599221/148211736-f73bcba2-94f4-4492-a009-e14446c487fa.png)
Blender:2.93

**Comment by yanchxx** [comment]
能截一下3D人物所在的界面看一下吗？

**Comment by jason870509** [comment]
> 能截一下3D人物所在的界面看一下吗？
![image](https://user-images.githubusercontent.com/42599221/148220574-ffdd1238-5f25-4b4f-9757-5ed17a02a4d8.png)

**Comment by yanchxx** [comment]
不懂为啥，我刚刚下载了blender 2.93的试了一下，果然出了问题。我重新导入了一下模型，现在重新上传了，你再试试看

**Comment by jason870509** [comment]
感谢您的积极处理与帮助，看起来是版本问题。
刚测试了虽然还是有报错，不过是可以正常运行了，我再多尝试些，非常感激，已解决!
