### ISSUE TITLE
What is the role of server.py？

### ISSUE THREAD

**Issue by littlejiumi** [yanchxx/CDBA#8]
Thanks for your wonderful work! I follow your instruction and run the beta.blender in Blender. But I don't run server.py yet.
![image](https://user-images.githubusercontent.com/36367749/149088270-fb584d25-e73a-4edd-8a99-99b5821b57f3.png)

**Comment by yanchxx** [comment]
This is the default animation I used for testing. When you pass in data using server.py, you can see the characters in Blender change as the data is transferred, proving that the transfer is successful.

**Comment by littlejiumi** [comment]
Thanks. What specific steps are required to achieve this effect with my own .npy file? （How can I use my .npz to generate the .blend file as yours?）

**Comment by yanchxx** [comment]
I've updated it, so now if you want to use your own ROMP's .npz file, just replace the npz_path in server.py.

**Comment by littlejiumi** [comment]
Thank you so much!
