### ISSUE TITLE
Could I ask for a detailed instruction on how to change the 3D Character?

### ISSUE THREAD

**Issue by jakuchuxia** [yanchxx/CDBA#9]
Also, I would like to know if there is a way to replace the 3D Character before I run the script and process the video so that I don't have to manually change it every time?

**Comment by yanchxx** [comment]
I'm developing a fully automated [website](http://120.53.123.49:8000/upload/animation) so you can give it a try.
As for the detailed operation, this requires you to be familiar with Blender, otherwise it will be very difficult for you to handle any problems that arise, so I recommend you to read the lessons I give in the acknowledgements first.

**Comment by jakuchuxia** [comment]
Thank you for your replying, I will take a try at the website!

**Comment by DongshengXiao** [comment]
Hi, is there an easy way to replace the 3D characters with just SMPL 3D mesh model? Thanks for your help.

**Comment by yanchxx** [comment]
> Hi, is there an easy way to replace the 3D characters with just SMPL 3D mesh model? Thanks for your help.

You can use this [addon](https://github.com/Meshcapade/SMPL_blender_addon) to import SMPL and change its name to Armature.

![image](https://user-images.githubusercontent.com/38496769/150262826-657460ae-afa6-4fb3-b316-0f6dab58c215.png)

The global translation seems to be wrong,you should change the global translation to [0,0,0] in server.py.

![image](https://user-images.githubusercontent.com/38496769/150262859-c5f127db-98f0-4310-b96d-51adf5ea0aa2.png)

When the data transfer is complete and SMPL is not in the view I set, select it in the sidebar and press the "/" key（in 3D viewport) to find it.

**Comment by DongshengXiao** [comment]
Thank you very much for your reply.

**Comment by jakuchuxia** [comment]
> > Hi, is there an easy way to replace the 3D characters with just SMPL 3D mesh model? Thanks for your help.
> 
> You can use this [addon](https://github.com/Meshcapade/SMPL_blender_addon) to import SMPL and change its name to Armature.
> 
> ![image](https://user-images.githubusercontent.com/38496769/150262826-657460ae-afa6-4fb3-b316-0f6dab58c215.png)
> 
> The global translation seems to be wrong,you should change the global translation to [0,0,0] in server.py.
> 
> ![image](https://user-images.githubusercontent.com/38496769/150262859-c5f127db-98f0-4310-b96d-51adf5ea0aa2.png)
> 
> When the data transfer is complete and SMPL is not in the view I set, select it in the sidebar and press the "/" key（in 3D viewport) to find it.

I tried your method with a new video, but the model only move in place and doesn't seem to move forward. Also, after I run the addon, the model shifted further away from the original point. This problem still exists after I change the global translation to [0,0,0]. 
![123](https://user-images.githubusercontent.com/89444000/151110422-563ce331-fa0a-4bb9-b6ed-743614dd4fd5.PNG)
Any help will be appreciated.

**Comment by yanchxx** [comment]
Changing the global translation to [0,0,0] prevents the model from moving in space. Its initial spatial position is also uncertain, so it can only be found by pressing key / , then CTRL(Command) + Shift +0 (0 on the numpad or open the emulate numpad) to shift the background back.
![image](https://user-images.githubusercontent.com/38496769/151112613-cd18fe1e-788e-4266-b85a-f6c714d5a6b8.png)

As for why the spatial location of this SMPL model is incompatible with my model's spatial location, I guess its root node is `root` while my model's root node is `Pelvis`.

So what are you trying to do? My website may be able to solve your problem, if you need, I can help you operate on my website first, with your own model and video.

**Comment by DongshengXiao** [comment]
![image](https://user-images.githubusercontent.com/49736716/151464225-0c84718b-2d57-44ac-9623-5e3b43709f01.png)

Hi, can we use the 3D character like this example instead of the demo one? Thank you very much.

**Comment by yanchxx** [comment]
> ![image](https://user-images.githubusercontent.com/49736716/151464225-0c84718b-2d57-44ac-9623-5e3b43709f01.png)

我有点不太理解，用那个插件导入的不是这个SMPL模型吗？只不过材质不太一样，所以显示上有点区别。
然后空间位置我确实也不太理解为什么不对，等我有空的时候再优化一下吧，提供个SMPL模型版本的也可以。

**Comment by DongshengXiao** [comment]
太感谢了，那会非常有帮助，期待SMPL模型版本。

**Comment by yanchxx** [comment]
更新了SMPL模型版本了

**Comment by DongshengXiao** [comment]
太棒了！多谢！！
